#redir-port: 7892
#port: 7890
#socks-port: 7891
#mixed-port: 7893
#mode: rule
#log-level: silent
#allow-lan: true
#external-controller: 0.0.0.0:9090
#secret: '123456'
#bind-address: "*"
#ipv6: false
#dns:
#  enable: true
#  ipv6: false
#  enhanced-mode: redir-host
#  listen: 127.0.0.1:7874
#  fallback-filter:
#    geoip: false
#    ipcidr:
#    - 240.0.0.0/4
#  nameserver:
#  - https://cloudflare-dns.com/dns-query
#  - https://dns.google/dns-query
#  - tls://1.1.1.1:853
#  - tls://8.8.8.8:853
#  fallback:
#  - tcp://1.1.1.1
#  - tcp://8.8.8.8
#  - 1.1.1.1
#  - 8.8.8.8

proxy-groups:
- name: FINAL
  type: select
  proxies:
  - Vmess
  - Trojan  
  - SS
  - SSR
  - Other
  - Auto_Vmess
  - Auto_Trojan
  - Auto_SS
  - Auto_SSR
  - Auto_All
  - LoadBalance_Vmess
  - LoadBalance_Trojan
  - LoadBalance_SS
  - LoadBalance_SSR

- name: Vmess
  type: select
  use:
  - Server_Vmess

- name: Trojan
  type: select
  use:
  - Server_Trojan

- name: SS
  type: select
  use:
  - Server_SS

- name: SSR
  type: select
  use:
  - Server_SSR

- name: Other
  type: select
  use:
  - Server_Other

- name: Auto_Vmess
  type: url-test
  tolerance: 50
  use:
  - Server_Vmess

- name: Auto_Trojan
  type: url-test
  tolerance: 50
  use:
  - Server_Trojan

- name: Auto_SS
  type: url-test
  tolerance: 50
  use:
  - Server_SS

- name: Auto_SSR
  type: url-test
  tolerance: 50
  use:
  - Server_SSR

- name: Auto_All
  type: url-test
  tolerance: 50
  use:
  - Server_Vmess
  - Server_Trojan
  - Server_SS
  - Server_SSR
  - Server_Other

- name: LoadBalance_Vmess
  type: load-balance
  strategy: consistent-hashing #round-robin
  disable-udp: false
  use:
  - Server_Vmess

- name: LoadBalance_Trojan
  type: load-balance
  strategy: consistent-hashing #round-robin
  disable-udp: false
  use:
  - Server_Trojan

- name: LoadBalance_SS
  type: load-balance
  strategy: consistent-hashing #round-robin
  disable-udp: false
  use:
  - Server_SS

- name: LoadBalance_SSR
  type: load-balance
  strategy: consistent-hashing #round-robin
  disable-udp: false
  use:
  - Server_SSR

proxy-providers:
  Server_Vmess:
    type: http
    url: https://raw.githubusercontent.com/djoeni/djtest/main/Server_Vmess.yaml
    path: ./Server_Vmess.yaml
    health-check:
      enable: true
      interval: 300
      #lazy: true
      url: http://www.gstatic.com/generate_204
      
  Server_Trojan:
    type: http
    url: https://raw.githubusercontent.com/djoeni/djtest/main/Server_Trojan.yaml
    path: ./Server_Trojan.yaml
    health-check:
      enable: true
      interval: 300
      #lazy: true
      url: http://www.gstatic.com/generate_204

  Server_SS:
    type: http
    url: https://raw.githubusercontent.com/djoeni/djtest/main/Server_SS.yaml
    path: ./Server_SS.yaml
    health-check:
      enable: true
      interval: 300
      #lazy: true
      url: http://www.gstatic.com/generate_204

  Server_SSR:
    type: http
    url: https://raw.githubusercontent.com/djoeni/djtest/main/Server_SSR.yaml
    path: ./Server_SSR.yaml
    health-check:
      enable: true
      interval: 300
      #lazy: true
      url: http://www.gstatic.com/generate_204

  Server_Other:
    type: http
    url: https://raw.githubusercontent.com/djoeni/djtest/main/Server_Other.yaml
    path: ./Server_Other.yaml
    health-check:
      enable: true
      interval: 300
      #lazy: true
      url: http://www.gstatic.com/generate_204

rule-providers:
  Rules_Lan:
    behavior: ipcidr
    type: http
    url: https://raw.githubusercontent.com/djoeni/djtest/main/Rules_Lan.yaml
    path: ./Rules_Lan.yaml

  Rules_Reject:
    behavior: domain
    type: http
    url: https://raw.githubusercontent.com/djoeni/djtest/main/Rules_Reject.yaml
    path: ./Rules_Reject.yaml

rules:
- RULE-SET,Rules_Lan,DIRECT,no-resolve
- RULE-SET,Rules_Reject,REJECT
- MATCH,FINAL
